services:
  api:
    container_name: api
    build:
      context: .
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - error_responses:/app/error_responses
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

    restart: always

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - nginx_logs:/var/log/nginx
    ports:
      - "8000:8000"
    depends_on:
      - api
    restart: always

volumes:
  nginx_logs:
  error_responses:
